### ISSUE TITLE
Pup Fails to Run on an M1 Mac in Big Sur

### ISSUE THREAD

**Issue by alexclst** [ericchiang/pup#147]
I cannot get `pup` to run on my M1 Mac mini. I downloaded the latest build from the Downloads page, but I'm always getting `Segmentation fault: 11` when run in Bash, or `fish: 'pup' terminated by signal SIGSEGV (Address boundary error)` when run in my default shell, Fish. I've allowed it in Security preferences, but there seems to be a crash going on. I tried installing with `brew`, but that gets stuck with the install of Go on the ARM architecture.

**Comment by gromgit** [comment]
Have you installed Rosetta 2? https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/

I don't have an M1, but one thing I keep hearing is that you have to quit and restart Terminal after installing Rosetta, for it to work.

`pup` M1 bottles on Homebrew will have to wait for Go 1.16, since that's the first officialy supported release on M1.

**Comment by alexclst** [comment]
Yes, I have Rosetta 2. But I've found a replacement tool for my use for `pup`, so all is well.

**Comment by ryandesign** [comment]
Users on Intel report crashes too. See #85, #123.
