### ISSUE TITLE
Is slice{} no longer included?

### ISSUE THREAD

**Issue by bikeseat** [EricChiang/pup#30]
on laptop
````
[foo@bar ]$ pup --version
0.3.2
[foo@bar ]$ curl -s www.google.com | pup a slice{0}
<a class="gb1" href="http://www.google.com/imghp?hl=en&amp;tab=wi">
  Images
  </a>
[foo@bar ]$
````
on desktop
````
[foo@bar pup]$ ./pup --version
0.3.7
[foo@bar pup]$ curl -s www.google.com | ./pup a slice{0}
[foo@bar pup]$
````

**Comment by EricChiang** [comment]
With the inclusion of many advanced css selectors a bit back, pup has dropped slices. There were clunky and had quite a few bugs.

Use any of the following selectors instead of slices.

```
pup ':nth-child(n)'
pup ':nth-of-type(n)'
pup ':nth-last-child(n)'
pup ':nth-last-of-type(n)'
```

 `n` can be a number, "even", "odd", or an expression such as "2n+1". You can play around with the behavior here: http://css-tricks.com/examples/nth-child-tester/#
