### ISSUE TITLE
EOF when using find and xargs

### ISSUE THREAD

**Issue by nwmcsween** [ericchiang/pup#65]
`find ./ -name "*" -type f -print0 | xargs -0 pup 'style text{}'`
Expected: returns style text
Actual: returns EOF for every file passes to pup

**Comment by ericchiang** [comment]
xargs is just appending the arguments to the command you're giving it. Pup read's from stdin.

For instance if find returns the following

```
$ find . -type f
./index.html
```

Then

```
$ find . -type f | xargs pup 'style text{}'
```

Is equivalent to

```
$ pup 'style text{}' index.html
```

And, because you're using the pipe, pup hits an EOF when reading from stdin while trying to parse the HTML.

This also causes the same error

```
$ echo -n "" | pup 'style text{}' index.html
EOF
```

You want

```
$ for file in $( find . -type f); do cat $file | pup 'style text{}'; done
```
